### ISSUE TITLE
🦊 Firefox?

### ISSUE THREAD

**Issue by whyman** [yaggytter/chrome-extension-awssso#1]
Hey,

Any chance of supporting firefox? Would be great to have it there.

Thanks!

**Comment by yaggytter** [comment]
@whyman 
Thanks for your request. I will try to support Firefox in the near future.

**Comment by yaggytter** [comment]
@whyman 
I have created Firefox version. You can install it from following URL.
https://addons.mozilla.org/firefox/addon/extension-for-aws-sso/

And, the source code is below.
https://github.com/yaggytter/chrome-extension-awssso/tree/forfirefox

**Comment by whyman** [comment]
@yaggytter thanks, I've been using it this whole time 

Appreciate your effort
