### ISSUE TITLE
Extension doesn't work on AWS Health Dashboard

### ISSUE THREAD

**Issue by garypiner** [yaggytter/chrome-extension-awssso#10]
AWS Health Dashboard has the following URL https://health.aws.amazon.com/health/home#/account/dashboard/other-notifications
Which isn't included on the allowed URLs
https://*.awsapps.com/*
https://*.console.aws.amazon.com/*

**Comment by yaggytter** [comment]
Thanks for the information. I will fix it soon.
@garypiner

**Comment by yaggytter** [comment]
@garypiner
I have fixed it as v1.3.0.
