### ISSUE TITLE
only the 1st color setting affect

### ISSUE THREAD

**Issue by hellsp** [yaggytter/chrome-extension-awssso#19]
Version 1.3.1 on Chorme 113.0.5672.126, MacOS 13.3.1 (a) 
the color setting seems only works the first line.
e.g. the title color only change in `Development` account

> {
> 	".*Development.*": "green",
> 	".*Production.*": "red"
> }

btw, no issue the same version on Firefox

**Comment by yaggytter** [comment]
@hellsp 
Thank you for the report. I found a cause of this on this line https://github.com/yaggytter/chrome-extension-awssso/blob/20bf3da8c6a7cae0deb98e2c1edb11fa2e70a091/content.js#L218 . so I will fix it asap as v1.3.2

**Comment by yaggytter** [comment]
@hellsp 
Fixed and released it as v1.3.2. Thanks!
