### ISSUE TITLE
Extension stopped working

### ISSUE THREAD

**Issue by gw-bcharboneau** [yaggytter/chrome-extension-awssso#21]
Appreciate the work on this extension it was working well for a while. recently it stopped working for me. I tried uninstalling and re-installing it to see if that would fix and it did not. Favorite, Header Color, and Account/Role Section are not changing even though i have it set correctly.

If there is anything i can do to provide debugging info, let me know.

**Comment by yaggytter** [comment]
It is working in my environment. (M1 Mac Chrome / Firefox)
What environment are you using?
@gw-bcharboneau 

Does anyone have the same problem?

**Comment by yaggytter** [comment]
I think it was fixed by [#33](https://github.com/yaggytter/chrome-extension-awssso/issues/23).
