### ISSUE TITLE
Do not see account name nor account# under firefox

### ISSUE THREAD

**Issue by MigaFr** [yaggytter/chrome-extension-awssso#22]
Hi,

First I will thank you for this good extension !

I'm usually use firefox and have added this extension on both firefox and Chrome.

Under Chrome (version 1.3.2) we see on the top right :
SSO:"My Role" @ "Account name" ("account #")

But under Firefox (version 1.3.1) we have on the top  right : 
"My Role" / "My email"
Wish is useless then what we have under chrome, having name/# of the account is really useful (I use dozen of different accounts).

Is it normal ?

Regards,

**Comment by yaggytter** [comment]
It is working in my environment. (M1 Mac Chrome / Firefox)
What environment are you using?
@MigaFr 

regarding https://github.com/yaggytter/chrome-extension-awssso/issues/21

**Comment by yaggytter** [comment]
I think it was fixed by [#33](https://github.com/yaggytter/chrome-extension-awssso/issues/23).

**Comment by yaggytter** [comment]
I was wrong. Firefox version is not released yet.

**Comment by MigaFr** [comment]
After raz firefox and re-install it seems OK. thanks :-)

**Comment by MigaFr** [comment]
oups raz it's french :/ "Remise A Zero"

**Comment by peterbev** [comment]
Hi @yaggytter, I notice 1.3.1 is still the latest Firefox version at [addons]( https://addons.mozilla.org/), do you have any idea when we might see 1.3.3?

**Comment by yaggytter** [comment]
Hi @peterbev, I just released the version 1.3.3. https://addons.mozilla.org/ja/firefox/addon/extension-for-aws-sso/
