### ISSUE TITLE
Not working for domain eu-west-1.console.aws.amazon.com

### ISSUE THREAD

**Issue by vitaly-zdanevich** [yaggytter/chrome-extension-awssso#26]
![image](https://github.com/yaggytter/chrome-extension-awssso/assets/3514015/bce135f3-4ff5-4d05-93b2-c013c73c3e70)

![image](https://github.com/yaggytter/chrome-extension-awssso/assets/3514015/c6d647b2-8847-4ead-ad84-6f55ac606ccc)

**Comment by yaggytter** [comment]
It's working on my browsers Chrome and Firefox.

<img width="1004" alt="image" src="https://github.com/yaggytter/chrome-extension-awssso/assets/7324799/8f500093-0dd3-4ae5-8bfb-5ee6cc1b3808">


What is your environment?
@vitaly-zdanevich

**Comment by vitaly-zdanevich** [comment]
Yep, it works for me now.
