### ISSUE TITLE
AWS Console design was changed

### ISSUE THREAD

**Issue by yaggytter** [yaggytter/chrome-extension-awssso#3]
This extension dose not work because AWS Console design was changed.

**Comment by yaggytter** [comment]
fixed it with https://github.com/yaggytter/chrome-extension-awssso/releases/tag/v1.1

**Comment by peterbev** [comment]
Hi @yaggytter, are you actively working on resolving this issue?

**Comment by yaggytter** [comment]
Hi @peterbev,

Yes. I already fixed and released it as v1.1 on chrome web store.
So I will close this issue.
