### ISSUE TITLE
Custom colours

### ISSUE THREAD

**Issue by peterbev** [yaggytter/chrome-extension-awssso#4]
I work with a **lot** of accounts, would it be possible to allow specifying a list of regexes and the colour to set the header to if they match?
eg:
```
{
"^Prod.*": "maroon",
"^Int.*": "darkblue"
}
```

**Comment by asherber** [comment]
I was going to open a feature request just for regexes to indicate production accounts (ours end in `prod`, not `production`), but this suggestion is more flexible!

**Comment by yaggytter** [comment]
Thank you for your suggestion. I will try to implement it.

**Comment by yaggytter** [comment]
I have implemented a color customization function.  It will be published on Chrome Web Store as v1.2 soon.

**Comment by peterbev** [comment]
That's great @yaggytter. Do you have plans to provide same functionality for firefox? That's my preferred browser as Chrome has no functionality to match their multi-account container add-on...

**Comment by asherber** [comment]
@peterbev Take a look at [https://chrome.google.com/webstore/detail/multilogin/ijfgglilaeakmoilplpcjcgjaoleopfi](https://chrome.google.com/webstore/detail/multilogin/ijfgglilaeakmoilplpcjcgjaoleopfi)  I use this all the time with AWS accounts.

**Comment by yaggytter** [comment]
@peterbev 
I have published Firefox version as v1.2 on https://addons.mozilla.org/ja/firefox/addon/extension-for-aws-sso/ . I usually use Chrome so let me know if you have problem when you are using this.
Thanks!

**Comment by yaggytter** [comment]
@asherber I didn't know this extension. I will try to use this. Thank you for your information!

**Comment by peterbev** [comment]
@yaggytter Is there a way to update the regex/colour mapping short of updating the code and rebuilding? 

@asherber interesting, I hadn't seen that before. It does make using multiple accounts somewhat easier, although the fact that nothing persists once the tab is closed means every time you open a tab for an account, you have to reauthenticate (unless I'm missing something?). The firefox multi-account container add-on allows you to create containers that you then re-use, so as I'm rarely logged into more than 5 accounts simultaneously I have 5 containers names AWS#1 - AWS#5, and once I've completed MFA I use https://addons.mozilla.org/en-US/firefox/addon/cookie-quick-manager/ to copy my authentication cookies between containers meaning I can access my accounts and don't need to authenticate again until my MFA token expires. The multi-account container add-on also colour codes the tabs which is a nice touch.

**Comment by asherber** [comment]
I think the new extension version is not yet available -- web store still says 1.1, and the new version is 1.2. The new version has an options dialog where you can enter the json map for the regexes and colors you want.

The multi account extension is supposed to give you an isolated copy of your cookie jar for each tab you open with it, but you're right that it doesn't seem to correctly copy the cookies for AWS. I usually put each account into a new tab group, which gets the color coding and grouping that Firefox has. Any new tabs spawned from the current one (e.g, ctrl-click a link in the AWS console) will stay in the same group and keep the same cookies. It's not a perfect system, but it works for me.

**Comment by yaggytter** [comment]
You can use the function on the add-ons preference page for this add-on if you already use v1.2 which is already published on  https://addons.mozilla.org/ja/firefox/addon/extension-for-aws-sso/  .
![image](https://user-images.githubusercontent.com/7324799/143729505-60abc1f2-02dc-4236-8d97-2b5677894e18.png)

Chrome version v1.2 is still under review by chrome web store.

**Comment by peterbev** [comment]
My bad, I needed to refresh the extensions page after updating. Works a treat, thanks :thumbsup:

**Comment by yaggytter** [comment]
Chrome version is also just published on chrome web store.
Thank you for your support.
