### ISSUE TITLE
Not working for Inspector classic

### ISSUE THREAD

**Issue by peterbev** [yaggytter/chrome-extension-awssso#7]
Just noticed that the add-in isn't working for the Inspector classic console, although v2 _**does**_ work
Not working - Classic:  https://eu-west-2.console.aws.amazon.com/inspector/home?region=eu-west-2#/
Working - v2: https://eu-west-2.console.aws.amazon.com/inspector/v2/home?region=eu-west-2#/

**Comment by yaggytter** [comment]
@peterbev 
Thank you for the notification.
It seems to be working already. I guess the Inspector classic console design was also changed.
