### ISSUE TITLE
somehow this add-on doesn't work on Firefox 101.0 (64-bit) on MacOS

### ISSUE THREAD

**Issue by hellsp** [yaggytter/chrome-extension-awssso#8]

**Comment by yaggytter** [comment]
I confirmed that it is working on my computer with M1 Mac, MacOS 12.3.1 and Firefox 101.0(64-bit).
 
<img width="482" alt="image" src="https://user-images.githubusercontent.com/7324799/172771190-f640d692-fa84-42d2-9175-430b990ef470.png">
<img width="215" alt="image" src="https://user-images.githubusercontent.com/7324799/172771242-07166349-d45f-419f-bea1-6100d80f4333.png">

Can you try again from SSO login?
@hellsp

**Comment by hellsp** [comment]
it still can't work, just show as this, no color, no account name
![image](https://user-images.githubusercontent.com/3829078/172967612-846745ad-b805-457f-8388-971705a043d7.png)



this is my firefox:
![image](https://user-images.githubusercontent.com/3829078/172967969-e0df0c0d-0cdd-4a21-90ab-69001c2b4bc8.png)





and this is my laptop, it's Intel chip:
![image](https://user-images.githubusercontent.com/3829078/172967744-66920fbb-0a44-4e80-b988-70e631f8da37.png)


btw, this is my config(it works in Chrome) 
```json
{
	".*Development.*": "green",
	".*Infrastructure.*": "red",
	".*Production.*": "red",
	".*QA.*": "gold",
	".*Staging.*": "orange",
	".*dev.*": "green",
	".*prd.*": "red",
	".*production.*": "red",
	".*qa.*": "gold",
	".*stg.*": "orange"
}
```

**Comment by yaggytter** [comment]
It worked on my PC with the same version and settings as yours. I guess, it is in conflict with another add-on function, or the permissions of this add-on are not enough. Can you check it?

<img width="873" alt="image" src="https://user-images.githubusercontent.com/7324799/173418066-ff38edd8-3f22-4d0b-b49d-3b4adc11d788.png">

**Comment by yaggytter** [comment]
If you see any error messages in your browser's developer tools console, could you please post them here?

**Comment by hellsp** [comment]
hmm... I only have this one add-on 🤔 

![image](https://user-images.githubusercontent.com/3829078/173477725-e5297f82-e64b-490a-b579-4e06d657f968.png)



and this is the permission: 
![image](https://user-images.githubusercontent.com/3829078/173477538-d9c2b7c3-5c3a-4420-af0f-03b11dffe258.png)

**Comment by hellsp** [comment]
btw, I'm on Intel Chip Macbook 
![image](https://user-images.githubusercontent.com/3829078/173477996-e2e528bb-1ddc-4f8a-8f61-a837da5d63ae.png)

**Comment by yaggytter** [comment]
It also worked on my Intel chip Macbook. There are error messages in your browser's developer tools console? could you please post them here?

**Comment by hellsp** [comment]
there's no error, just a few warnings: 
![image](https://user-images.githubusercontent.com/3829078/174697594-33f09f8d-7828-4d0f-8283-baa782059ac8.png)

**Comment by hellsp** [comment]
wait, got some errors after retrying 
![image](https://user-images.githubusercontent.com/3829078/174724794-af14ff76-9b2e-46b3-a4af-6f1a3bc94285.png)

**Comment by yaggytter** [comment]
It seems failure with timed out at https://github.com/yaggytter/chrome-extension-awssso/blob/a3ef63f38bda872a5a4da7e4fe2f0aa218457e94/content.js#L44 .
I don't know why I can't reproduce it on my environment...

**Comment by hellsp** [comment]
it works  very well now!

**Comment by calebworks** [comment]
Just for anyone else having this issue, I had to restart Firefox after installing the extension before it would work.
