### ISSUE TITLE
Feature request: Favorites list for accounts in SSO login page

### ISSUE THREAD

**Issue by krastgeo-flutterint** [yaggytter/chrome-extension-awssso#9]
One thing that would really be useful (to me at least) will be the ability to able mark/check favorite AWS account in the SSO login page so that they show on top.

As I manage 100+ accounts, and frequently use few of them, this feature will ease my navigation.
AWS search field is ok, but far from optimal. Also, when open the SSO page, you need to click on "AWS Accounts" box to expand them all, which also is sort of useless.

As for the UI implementation, several ways are possible:
- a checkbox or some kind of icon after the account, to add them in your "favorites"
- configuration text field to match account name, comma separated list or regex support

**Comment by yaggytter** [comment]
I want this function too. So I will try to implement it on next release.

**Comment by yaggytter** [comment]
![image](https://user-images.githubusercontent.com/7324799/196418879-c955b567-0872-47f9-a488-9641eb487f8f.png)
![image](https://user-images.githubusercontent.com/7324799/196419131-30770fac-97ef-4d6e-a8c3-6d5b5e317052.png)

I have implemented it using option dialog to config favorites list as v1.3.0
@georgik-flutter
